// website/App.svelte
<script lang="ts">
  import DemoWidget from './components/DemoWidget.svelte'
</script>

<section class="app">
  <header>
    <h1>784</h1>
  </header>

  <main>
    <DemoWidget />
  </main>

  <a
    href="/book"
    class="book-link"
  >
    READ: An Introduction to Neural Networks
  </a>

  <footer>
    <a
      class="external"
      href="https://github.com/dansalias/784"
      target="_blank"
    >
      Source on GitHub
    </a>
  </footer>
</section>

<style>
  .app {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 2rem;

    > main {
      margin: 0 0 1rem;
    }

    > .book-link {
      text-decoration: none;
    }

    > .book-link:hover {
      text-decoration: underline;
    }
  }
</style>

// website/components/App.vue
<template>
  <div
    class="
      grid min-h-dvh py-4
      bg-linear-135 from-cyan-300 to-emerald-100 bg-fixed
      text-center text-indigo-900
    ">
    <div class="m-auto">
      <h1 class="mb-8 font-display text-6xl">784</h1>
      <app-demo />
      <p class="mt-12 text-sm">
        <a
          class="underline decoration-dotted"
          href="https://github.com/dansalias/784"
          target="_blank"
        >
          Source on GitHub
        </a>
      </p>
    </div>
  </div>
</template>

<script lang="ts" setup>
  import AppDemo from './AppDemo.vue'
</script>
